### ISSUE TITLE
Why invoked

### ISSUE THREAD

**Issue by EFF** [mentum/invoked-website#9]
We should explain why INVOKED exists .. 

i would try to reproduce something like the "why kubernetes section" on http://kubernetes.io/

I really like their termes

**Comment by EFF** [comment]
@slvnperron

**Comment by slvnperron** [comment]
# Why Invoked.io ?

## Unobtrusive

Invoked doesn't need you to modify or adapt your existing code base. It makes it painless for you to transition your functions execution location.

## Open-source

The core behind Invoked.io is completely open-source. Found a bug, doesn't like something or want a new feature? You can actually do something about it.

## Extensible

Because of Invoked's open-model design, it is extremely easy to build modules that sit on top of it.
